"use client";

import React, { useMemo, useState, useEffect } from "react";
import { useChat } from "../providers/ChatProvider";
import dayjs from 'dayjs';
import relativeTime from 'dayjs/plugin/relativeTime';
import { Plus, Trash2, MessageSquare, Table as TableIcon, ExternalLink } from 'lucide-react';
import { useSheet } from "../providers/SheetProvider";
import { useFirebase } from "../providers/FirebaseProvider";
import { useDialog } from "../providers/DialogProvider";
import SpreadsheetManagerModal from "./SpreadsheetManagerModal";
dayjs.extend(relativeTime);

interface ChatSidebarProps {
  embedded?: boolean;
  peek?: boolean; // compact mode that still shows titles
}

const ChatSidebar: React.FC<ChatSidebarProps> = ({ embedded = false, peek = false }) => {
  const { sessions, currentSessionId, setCurrentSessionId, createSession, deleteSession, ensureSession } = useChat();
  const { user } = useFirebase();
  const { defaultSpreadsheetId, setDefaultSpreadsheetId } = useSheet();
  const { confirm } = useDialog();
  const [creating, setCreating] = useState(false);
  const [spreadsheets, setSpreadsheets] = useState<Array<{ id: string; spreadsheetId: string; title?: string }>>([]);
  const [spreadsheetsLoading, setSpreadsheetsLoading] = useState(false);
  const [managerOpen, setManagerOpen] = useState(false);

  // Service account UI moved into SpreadsheetManagerModal

  // Subscribe to user's spreadsheets list in Firestore
  useEffect(() => {
    let unsub: undefined | (() => void);
    (async () => {
      if (!user) { setSpreadsheets([]); return; }
      setSpreadsheetsLoading(true);
      const { collection, onSnapshot } = await import('firebase/firestore');
      const { db } = await import('../providers/FirebaseProvider');
      const ref = collection(db, 'users', user.uid, 'options');
      unsub = onSnapshot(ref, (snap) => {
        const items = snap.docs.map(d => ({ id: d.id, ...(d.data() as any) }))
          .filter(x => typeof x.spreadsheetId === 'string')
          .map(x => ({ id: x.id, spreadsheetId: x.spreadsheetId as string, title: x.title as string | undefined }));
        setSpreadsheets(items);
        setSpreadsheetsLoading(false);
      });
    })();
    return () => { if (unsub) unsub(); };
  }, [user]);

  // Adding spreadsheet handled inside SpreadsheetManagerModal

  const removeSpreadsheetOption = async (id: string, spreadsheetId?: string) => {
    if (!user || !id) return;
    const { doc, deleteDoc } = await import('firebase/firestore');
    const { db } = await import('../providers/FirebaseProvider');
    await deleteDoc(doc(db, 'users', user.uid, 'options', id));
    if ((spreadsheetId && defaultSpreadsheetId === spreadsheetId) || (spreadsheets.length === 1 && defaultSpreadsheetId)) {
      setDefaultSpreadsheetId("");
    }
  };

  // Add/remove actions simplified: remove remains here

  const sortedSessions = useMemo(() => sessions, [sessions]);
  // Show all sessions, even if untitled, to avoid hiding active chats before AI title generation
  const visibleSessions = useMemo(() => sortedSessions, [sortedSessions]);

  const handleCreate = async () => {
    setCreating(true);
    try {
      const id = await createSession();
      if (id) setCurrentSessionId(id);
    } finally {
      setCreating(false);
    }
  };

  const handleSelect = async (id: string) => {
    // Selecting a chat should only switch the active session.
    // Do not call ensureSession here, as it may race and override the selection.
    setCurrentSessionId(id);
  };

  // Manual renaming removed; titles are generated by AI after first message

  // Copy service account removed from sidebar

  const renderSessionRow = (s: { id: string; title: string; updatedAt: string; lastMessageSnippet?: string }) => (
    <li key={s.id}>
      <div className={`group relative`}
           style={{ background: 'transparent' }}>
        <div
          role="button"
          tabIndex={0}
          onClick={() => handleSelect(s.id)}
          onKeyDown={(e) => { if (e.key === 'Enter' || e.key === ' ') handleSelect(s.id); }}
          className={`w-full text-left ${peek ? 'py-1.5' : 'py-2'} pl-3 flex items-center gap-2 cursor-pointer select-none`}
          style={{ background: 'transparent' }}
        >
          <div className="min-w-0 flex-1 pl-6">
            <div className="flex items-center gap-2">
              <div className={`truncate text-sm ${currentSessionId === s.id ? 'text-white font-semibold' : 'text-white/80 group-hover:text-white'}`}>{s.title || '...'}</div>
            </div>
          </div>
          {/* Right-side actions */}
          <div className="ml-auto flex items-center gap-1 shrink-0 mr-3">
            <button
              onClick={async (e) => {
                e.stopPropagation();
                const ok = await confirm({
                  title: 'Delete chat',
                  description: 'This will permanently delete this conversation. This action cannot be undone.',
                  tone: 'danger',
                  confirmText: 'Delete',
                  cancelText: 'Cancel',
                });
                if (ok) {
                  await deleteSession(s.id);
                  await ensureSession();
                }
              }}
              className={`grid place-items-center ${peek ? 'h-6 w-6' : 'h-7 w-7'} rounded-md border border-red-400/30 text-red-300 hover:text-red-200 hover:border-red-300/60 focus:outline-none focus:ring-1 focus:ring-red-300/30 leading-none`}
              title="Delete"
              aria-label="Delete chat"
            >
              <Trash2 className={`${peek ? 'w-3 h-3' : 'w-3 h-3'} block`} />
            </button>
          </div>
        </div>
        {/* no floating hover actions in simple list mode */}
      </div>
    </li>
  );

  if (embedded) {
    // Render the same UI in embedded mode
    return (
      <>
      <div className="flex flex-col h-full">
      <div className="flex items-center justify-between px-3 py-2 border-b border-white/10">
          <div className="flex items-center gap-2 text-sm font-semibold text-white">
            <MessageSquare className="w-4 h-4" />
            {!peek && 'Chats'}
             <span className="text-xs text-white/60">{!peek && `(${visibleSessions.length})`}</span>
          </div>
        <div className="shrink-0">
          <button
            onClick={handleCreate}
            className={`inline-flex items-center justify-center ${peek ? 'h-6 w-6' : 'h-7 w-7'} rounded-md border border-white/20 text-white/80 hover:text-white hover:border-white/50 bg-transparent`}
            disabled={creating}
            title="New Chat"
            aria-label="New chat"
          >
            <Plus className={`${peek ? 'w-3 h-3' : 'w-3.5 h-3.5'}`} />
          </button>
        </div>
        </div>
        <div className="flex-1 min-h-0 flex flex-col">
          <div className="flex-1 overflow-y-auto py-2">
            {/* Chats list under Chats header */}
            {visibleSessions.length === 0 ? (
              <div className="h-full flex items-center justify-center text-white/60 text-sm">No chats yet</div>
            ) : (
              <ul className="space-y-1">
              {visibleSessions.map((s) => renderSessionRow(s))}
              </ul>
            )}
          </div>

          {/* Spreadsheets manager header (list stays below) */}
          <div className="mt-2 mx-3 rounded-lg border border-white/10 bg-white/5 overflow-hidden">
            {/* Header */}
            <div className="px-3 py-2 flex items-center justify-between bg-white/5 border-b border-white/10">
              <div className="flex items-center gap-2 text-sm font-semibold text-white">
                <TableIcon className="w-4 h-4" />
                {!peek && 'Spreadsheets'}
                <span className="text-xs text-white/60">{!peek && `(${spreadsheets.length})`}</span>
              </div>
              <div className="flex items-center gap-1">
                <button
                  onClick={() => setManagerOpen(true)}
                  className={`inline-flex items-center justify-center px-2 ${peek ? 'h-6' : 'h-7'} rounded-md border border-white/20 text-white/80 hover:text-white hover:border-white/50`}
                  title="Manage spreadsheets"
                  aria-label="Manage spreadsheets"
                >
                  Manage
                </button>
              </div>
            </div>
            {/* Helper and adder moved to modal */}
            {/* List */}
            <div className="px-2 py-2 space-y-1 border-t border-white/10">
              {spreadsheetsLoading && (
                <div className="text-xs text-white/60 px-2">Loading spreadsheets…</div>
              )}
              {!spreadsheetsLoading && spreadsheets.length === 0 && (
                <div className="text-xs text-white/60 px-2">No spreadsheets yet. Add one above.</div>
              )}
              {spreadsheets.map((s) => {
                const active = defaultSpreadsheetId === s.spreadsheetId;
                return (
                  <div key={s.id} className={`group flex items-center gap-1.5 px-2 h-9 rounded-md ${active ? 'bg-white/10' : 'hover:bg-white/5'}`}>
                    <button
                      onClick={() => setDefaultSpreadsheetId(s.spreadsheetId)}
                      className="flex-1 text-left min-w-0"
                      title={s.title || s.spreadsheetId}
                    >
                      <div className={`truncate text-xs ${active ? 'text-white font-semibold' : 'text-white/80 group-hover:text-white'}`}>
                        {s.title || s.spreadsheetId}
                      </div>
                    </button>
                    <a
                      href={`https://docs.google.com/spreadsheets/d/${encodeURIComponent(s.spreadsheetId)}`}
                      target="_blank"
                      rel="noreferrer"
                      className="grid place-items-center h-6 w-6 rounded text-white/70 hover:text-white"
                      title="Open in Google Sheets"
                    >
                      <ExternalLink className="w-3 h-3" />
                    </a>
                    <button
                      onClick={async () => {
                        const ok = await confirm({
                          title: 'Remove spreadsheet',
                          description: 'Disconnect this spreadsheet from your account? You can add it again later.',
                          tone: 'warning',
                          confirmText: 'Remove',
                          cancelText: 'Cancel',
                        });
                        if (ok) await removeSpreadsheetOption(s.id, s.spreadsheetId);
                      }}
                      className="grid place-items-center h-6 w-6 rounded text-red-300 hover:text-red-200"
                      title="Remove"
                      aria-label="Remove spreadsheet"
                    >
                      <Trash2 className="w-3 h-3" />
                    </button>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </div>
      <SpreadsheetManagerModal open={managerOpen} onClose={() => setManagerOpen(false)} />
      </>
    );
  }

  // Non-embedded: render the same persistent sidebar (no open/close button)
  return (
    <div className="flex flex-col h-full">
      <div className="flex items-center justify-between px-3 py-2 border-b border-white/10">
        <div className="flex items-center gap-2 text-sm font-semibold text-white">
          <MessageSquare className="w-4 h-4" />
          {!peek && 'Chats'}
          <span className="text-xs text-white/60">{!peek && `(${visibleSessions.length})`}</span>
        </div>
        <div className="shrink-0">
          <button
            onClick={handleCreate}
            className={`inline-flex items-center justify-center ${peek ? 'h-6 w-6' : 'h-7 w-7'} rounded-md bg-emerald-600 text-white hover:bg-emerald-700 focus:outline-none focus:ring-1 focus:ring-emerald-400/40`}
            disabled={creating}
            title="New Chat"
            aria-label="New chat"
          >
            <Plus className={`${peek ? 'w-3 h-3' : 'w-3.5 h-3.5'}`} />
          </button>
        </div>
      </div>
      <div className="flex-1 min-h-0 flex flex-col">
        <div className="flex-1 overflow-y-auto px-0 py-2">
          {/* Chats list under Chats header */}
          {visibleSessions.length === 0 ? (
            <div className="h-full flex items-center justify-center text-white/60 text-sm">No chats yet</div>
          ) : (
            <ul className="space-y-1">
              {visibleSessions.map((s) => renderSessionRow(s))}
            </ul>
          )}
        </div>

        {/* Spreadsheets manager header (list stays below) */}
        <div className="mt-2 mx-3 rounded-xl border border-white/10 bg-white/5 overflow-hidden">
          {/* Manager header */}
          <div className="px-3 py-2 flex items-center justify-between bg-white/5 border-b border-white/10">
            <div className="flex items-center gap-2 text-sm font-semibold text-white">
              <TableIcon className="w-4 h-4" />
              {!peek && 'Spreadsheets'}
              <span className="text-xs text-white/60">{!peek && `(${spreadsheets.length})`}</span>
            </div>
            <div className="flex items-center gap-1">
              <button
                onClick={() => setManagerOpen(true)}
                className={`inline-flex items-center justify-center px-2 ${peek ? 'h-6' : 'h-7'} rounded-md border border-white/20 text-white/80 hover:text-white hover:border-white/50`}
                title="Manage spreadsheets"
                aria-label="Manage spreadsheets"
              >
                Manage
              </button>
            </div>
          </div>
          {/* Helper and adder moved to modal */}
        </div>

        {/* Connected spreadsheets list */}
        <div className="px-2 py-2 space-y-1 border-t border-white/10">
          {spreadsheetsLoading && (
            <div className="text-xs text-white/60 px-2">Loading spreadsheets…</div>
          )}
          {!spreadsheetsLoading && spreadsheets.length === 0 && (
            <div className="text-xs text-white/60 px-2">No spreadsheets yet. Add one above.</div>
          )}
          {spreadsheets.map((s) => {
            const active = defaultSpreadsheetId === s.spreadsheetId;
            return (
              <div key={s.id} className={`group flex items-center gap-1.5 px-2 h-9 rounded-md ${active ? 'bg-white/10' : 'hover:bg-white/5'}`}>
                <button
                  onClick={() => setDefaultSpreadsheetId(s.spreadsheetId)}
                  className="flex-1 text-left min-w-0"
                  title={s.title || s.spreadsheetId}
                >
                  <div className={`truncate text-xs ${active ? 'text-white font-semibold' : 'text-white/80 group-hover:text-white'}`}>
                    {s.title || s.spreadsheetId}
                  </div>
                </button>
                <a
                  href={`https://docs.google.com/spreadsheets/d/${encodeURIComponent(s.spreadsheetId)}`}
                  target="_blank"
                  rel="noreferrer"
                  className="grid place-items-center h-6 w-6 rounded text-white/70 hover:text-white"
                  title="Open in Google Sheets"
                >
                  <ExternalLink className="w-3 h-3" />
                </a>
                <button
                  onClick={() => removeSpreadsheetOption(s.id, s.spreadsheetId)}
                  className="grid place-items-center h-6 w-6 rounded text-red-300 hover:text-red-200"
                  title="Remove"
                  aria-label="Remove spreadsheet"
                >
                  <Trash2 className="w-3 h-3" />
                </button>
              </div>
            );
          })}
        </div>
      </div>
    <SpreadsheetManagerModal open={managerOpen} onClose={() => setManagerOpen(false)} />
    </div>
  );
};

export default ChatSidebar;
